library:
  source-dirs: src
tests:
  newstyping-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - newstyping
copyright: 2019 lnsf
maintainer: lnsf03@gmail.com
dependencies:
- yaml
- http-conduit
- bytestring
- aeson
- time
- ansi-terminal >= 0.9
- base >= 4.7 && < 5
name: newstyping
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: lnsf
github: lnsf/NewsTyping
license: MIT
executables:
  newstyping-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - random
    - newstyping
description: Please see the README on GitHub at <https://github.com/lnsf/newstyping#readme>
